var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var parseBmfontXml=require("parse-bmfont-xml"),HangulAtlasEditor=function(){HangulAtlasEditor.Initialize()};window.addEventListener("load",HangulAtlasEditor.bind(HangulAtlasEditor));HangulAtlasEditor.AlphabetType={None:-1,Consonant:0,Vowel:1};HangulAtlasEditor.RENDER_SPEED=16;HangulAtlasEditor.RENDER_STEP=10;HangulAtlasEditor.UNICODE_CONSONANTS="\u3131\u3132\u3133\u3134\u3135\u3136\u3137\u3138\u3139\u313a\u313b\u313c\u313d\u313e\u313f\u3140\u3141\u3142\u3143\u3144\u3145\u3146\u3147\u3148\u3149\u314a\u314b\u314c\u314d\u314e";
HangulAtlasEditor.UNICODE_VOWELS="\u314f\u3150\u3151\u3152\u3153\u3154\u3155\u3156\u3157\u3158\u3159\u315a\u315b\u315c\u315d\u315e\u315f\u3160\u3161\u3162\u3163";HangulAtlasEditor.UNICODE_ALPHABETS=HangulAtlasEditor.UNICODE_CONSONANTS+HangulAtlasEditor.UNICODE_VOWELS;HangulAtlasEditor.UNICODE_ALPHABET_START=12593;HangulAtlasEditor.UNICODE_ALPHABET_END=12687;HangulAtlasEditor.UNICODE_START=44032;HangulAtlasEditor.UNICODE_END=55203;HangulAtlasEditor.UNICODE_HEAD_RANGE=588;
HangulAtlasEditor.UNICODE_HEADS="\u3131\u3132\u3134\u3137\u3138\u3139\u3141\u3142\u3143\u3145\u3146\u3147\u3148\u3149\u314a\u314b\u314c\u314d\u314e";HangulAtlasEditor.UNICODE_BODY_RANGE=28;HangulAtlasEditor.UNICODE_BODIES="\u314f\u3150\u3151\u3152\u3153\u3154\u3155\u3156\u3157\u3158\u3159\u315a\u315b\u315c\u315d\u315e\u315f\u3160\u3161\u3162\u3163";HangulAtlasEditor.UNICODE_TAILS="\u3131\u3132\u3133\u3134\u3135\u3136\u3137\u3139\u313a\u313b\u313c\u313d\u313e\u313f\u3140\u3141\u3142\u3144\u3145\u3146\u3147\u3148\u314a\u314b\u314c\u314d\u314e";
HangulAtlasEditor.DKB_HORIZONTAL_LINE=30;HangulAtlasEditor.DKB_VERTICAL_LINE=18;
HangulAtlasEditor.DKB_TABLE={ALPHABET:{LINE_OFFSET:0,CHARSET:[HangulAtlasEditor.UNICODE_CONSONANTS,HangulAtlasEditor.UNICODE_VOWELS]},WITHOUT_TAIL:{HEAD:{LINE_OFFSET:2,CHARSET:["\u314f\u3150\u3151\u3152\u3153\u3154\u3155\u3156\u3163","\u3157\u315b\u3161","\u315c\u3160","\u3158\u3159\u315a\u3162","\u315d\u315e\u315f"]},BODY:{LINE_OFFSET:10,CHARSET:["\u3131\u314b","\u3132\u3134\u3137\u3138\u3139\u3141\u3142\u3143\u3145\u3146\u3147\u3148\u3149\u314a\u314c\u314d\u314e"]}},WITH_TAIL:{HEAD:{LINE_OFFSET:7,
CHARSET:["\u314f\u3150\u3151\u3152\u3153\u3154\u3155\u3156\u3163","\u3157\u315b\u315c\u3160\u3161","\u3158\u3159\u315a\u3162\u315d\u315e\u315f"]},BODY:{LINE_OFFSET:12,CHARSET:["\u3131\u314b","\u3132\u3134\u3137\u3138\u3139\u3141\u3142\u3143\u3145\u3146\u3147\u3148\u3149\u314a\u314c\u314d\u314e"]},TAIL:{LINE_OFFSET:14,CHARSET:["\u314f\u3151\u3158","\u3153\u3155\u315a\u315d\u315f\u3162\u3163","\u3150\u3152\u3154\u3156\u3159\u315e","\u3157\u315b\u315c\u3160\u3161"]}}};
HangulAtlasEditor.Initialize=function(a){"undefined"===typeof Rect||"undefined"===typeof Node?alert(Strings.HAE.FAILED_TO_LOAD_DEPENDENCIES):(this.DKBTexture=null,this.DKBVerticalUnit=this.DKBHorizontalUnit=0,this.IsDKBTextureLoaded=!1,this.FntAtlasTextures=null,this.IsFntAtlasTexturesLoaded=!1,this.FntData=null,this.IsFntDataLoaded=!1,this.Views={},this.Views.FontAtlasPreview=null)};
HangulAtlasEditor.GetGlyph=function(a){var b=a.charCodeAt(0),d;if(b<=this.UNICODE_ALPHABET_END){if(-1!==(d=this.UNICODE_CONSONANTS.indexOf(a)))return[!1,d];if(-1!==(d=this.UNICODE_VOWELS.indexOf(a)))return[!0,d]}b-=this.UNICODE_START;d=Math.floor(b/this.UNICODE_HEAD_RANGE);a=Math.floor(b/this.UNICODE_BODY_RANGE%HangulAtlasEditor.UNICODE_BODIES.length);b%=this.UNICODE_BODY_RANGE;return 0===b?[d,a]:[d,a,b-1]};HangulAtlasEditor.GetGlyphString=function(a){return this.ToGlyphString(this.GetGlyph(a))};
HangulAtlasEditor.ToGlyphString=function(a){if("boolean"===typeof a[0])return[a[0]?this.UNICODE_VOWELS.charAt(a[1]):this.UNICODE_CONSONANTS.charAt(a[1])];if(2===a.length)return[this.UNICODE_HEADS.charAt(a[0]),this.UNICODE_BODIES.charAt(a[1])];if(3===a.length)return[this.UNICODE_HEADS.charAt(a[0]),this.UNICODE_BODIES.charAt(a[1]),this.UNICODE_TAILS.charAt(a[2])]};HangulAtlasEditor.ClearFntAtlasTexture=function(){this.FntAtlasTextures=null;this.IsFntAtlasTexturesLoaded=!1};
HangulAtlasEditor.AddFntAtlasTexture=function(a,b){if(b&&""!==b.src&&0!==b.width&&0!==b.height)if(this.FntAtlasTextures=this.FntAtlasTextures||{},this.FntAtlasTextures[a]=b,this.FntData){for(var d=$jscomp.makeIterator(this.FntData.pages),e=d.next();!e.done;e=d.next())if(!(e.value in this.FntAtlasTextures)){this.IsFntAtlasTexturesLoaded=!1;return}this.IsFntAtlasTexturesLoaded=!0}else this.IsFntAtlasTexturesLoaded=!1};
HangulAtlasEditor.LoadFntXml=function(a){try{this.FntData=parseBmfontXml(a)}catch(b){alert(Strings.HAE.NOT_VALID_FNT);return}this.IsFntDataLoaded=!0};
HangulAtlasEditor.SetDKBAtlasTexture=function(a){a&&""!==a.src&&0!==a.width&&0!==a.height&&(0!==a.width%this.DKB_HORIZONTAL_LINE||0!==a.height%this.DKB_VERTICAL_LINE?alert(Strings.HAE.DKB_TEXTURE_SIZE_NOT_MATCH):(this.DKBTexture=a,this.DKBHorizontalUnit=a.width/this.DKB_HORIZONTAL_LINE,this.DKBVerticalUnit=a.height/this.DKB_VERTICAL_LINE,this.IsDKBTextureLoaded=!0))};
HangulAtlasEditor.DrawGlyph=function(a,b,d){if(this.IsDKBTextureLoaded){d=this.GetGlyph(d);var e=this.ToGlyphString(d);e=this.GetDKBAtlasData(d,e);d=this.Views.FontAtlasPreview.Context;e=$jscomp.makeIterator(e);for(var f=e.next();!f.done;f=e.next())f=f.value,d.drawImage(this.DKBTexture,this.DKBHorizontalUnit*f[1],this.DKBVerticalUnit*f[0],this.DKBHorizontalUnit,this.DKBVerticalUnit,a,b,this.DKBHorizontalUnit,this.DKBVerticalUnit)}};
HangulAtlasEditor.GetDKBAtlasData=function(a,b){switch(a.length){case 2:if("boolean"===typeof a[0]){var d=this.GetDKBLine(this.DKB_TABLE.ALPHABET,b[0]);return[[d,a[1]]]}d=this.GetDKBLine(this.DKB_TABLE.WITHOUT_TAIL.HEAD,b[1]);var e=this.GetDKBLine(this.DKB_TABLE.WITHOUT_TAIL.BODY,b[0]);return[[d,a[0]],[e,a[1]]];case 3:d=this.GetDKBLine(this.DKB_TABLE.WITH_TAIL.HEAD,b[1]);e=this.GetDKBLine(this.DKB_TABLE.WITH_TAIL.BODY,b[0]);var f=this.GetDKBLine(this.DKB_TABLE.WITH_TAIL.TAIL,b[1]);return[[d,a[0]],
[e,a[1]],[f,a[2]]];default:return null}};HangulAtlasEditor.GetDKBLine=function(a,b){var d=a.CHARSET,e;for(e=0;e<d.length;e++)if(-1!==d[e].indexOf(b)){e+=a.LINE_OFFSET;break}return e};
HangulAtlasEditor.GenerateFnt=function(a){var b=a.sizeLevel,d=a.fileName,e=a.offset,f=a.xAdvance,g=a.progress,k=a.pageCreated,h=a.done;a=a.error;if(!HangulAtlasEditor.IsDKBTextureLoaded||!HangulAtlasEditor.IsFntAtlasTexturesLoaded||!HangulAtlasEditor.IsFntDataLoaded)return alert(Strings.HAE.REQUIRED_ASSETS_NOT_LOADED),!1;try{"undefined"===typeof b?b=2:"string"===typeof b&&(b=parseInt(b));b+=8;7>b&&(b=7);13<b&&(b=13);b=Math.pow(2,b);var c={};c.events={progress:g,pageCreated:k,done:h,error:a};c.sizeLevel=
b;c.fileName=d;e=e||{x:0,y:0};c.offset=e;c.xAdvance=f;c.view=this.Views.FontAtlasPreview;c.view&&document.body.removeChild(view.Element);c.chars=this.FntData.chars;c.common=this.FntData.common;c.info=this.FntData.info;c.kernings=this.FntData.kernings;c.pages=this.FntData.pages;c.fullSpaceWidth=c.info.padding[1]+c.info.padding[3]+c.info.spacing[0]+c.info.spacing[0]%2;c.fullSpaceHeight=c.info.padding[0]+c.info.padding[2]+c.info.spacing[1]+c.info.spacing[1]%2;c.charResult=this.CopyObjectRecursive(c.chars);
c.pageResult=[];c.result={common:this.CopyObjectRecursive(c.common),info:this.CopyObjectRecursive(c.info),kernings:this.CopyObjectRecursive(c.kernings)};c.common.scaleW=b;c.common.scaleH=b;c.currentPage=new Node(new Rect(0,0,b,b));c.currentCanvas=new CanvasView(b,b);c.currentPageIndex=0;c.charInfo;c.charInfoResult;c.charCode;c.insertedRect;c.glyph=null;c.glyphString=null;c.atlasData=null;c.drawInfos=null;c.isKorean=!1;c.events.pageCreated&&c.events.pageCreated(c.currentPage,c.currentCanvas);c.events.progress&&
c.events.progress(0,45);setTimeout(this.DrawFntGlyph.bind(this,c),10*HangulAtlasEditor.RENDER_SPEED);return!0}catch(l){return a&&a(l),!1}};
HangulAtlasEditor.DrawFntGlyph=function(a,b){try{if(b||(b=0),b<a.chars.length){for(var d=0;d<this.RENDER_STEP&&!(b>=a.chars.length);d++){if(!a.drawInfos)if(a.charInfo=a.chars[b],a.charInfoResult=a.charResult[b],a.isKoreanFontData=null,a.charCode=a.charInfo.id,a.isKorean=a.charCode>=this.UNICODE_ALPHABET_START&&a.charCode<=this.UNICODE_ALPHABET_END&&this.GetAlphabetType(a.charCode)!==this.AlphabetType.None,a.isKorean||(a.isKorean=a.charCode>=this.UNICODE_START&&a.charCode<=this.UNICODE_END),a.isKorean){a.glyph=
this.GetGlyph(String.fromCharCode(a.charInfo.id));a.glyphString=this.ToGlyphString(a.glyph);a.atlasData=this.GetDKBAtlasData(a.glyph,a.glyphString);a.drawInfos=[];for(var e=$jscomp.makeIterator(a.atlasData),f=e.next();!f.done;f=e.next()){var g=f.value;"object"===typeof g&&a.drawInfos.push({x:this.DKBHorizontalUnit*g[1],y:this.DKBVerticalUnit*g[0],width:this.DKBHorizontalUnit,height:this.DKBVerticalUnit,texture:this.DKBTexture})}a.isKoreanFontData=!0}else a.drawInfos=[{x:a.charInfo.x,y:a.charInfo.y,
width:a.charInfo.width,height:a.charInfo.height,texture:this.FntAtlasTextures[a.pages[a.charInfo.page]]}];a.insertedRect=a.currentPage.insert_rect(new Rect(0,0,a.drawInfos[0].width+a.fullSpaceWidth,a.drawInfos[0].height+a.fullSpaceHeight));if(a.insertedRect){a.insertedRect=a.insertedRect.rect;for(var k=$jscomp.makeIterator(a.drawInfos),h=k.next();!h.done;h=k.next()){var c=h.value;a.currentCanvas.Context.drawImage(c.texture,c.x,c.y,c.width,c.height,a.insertedRect.x+a.info.spacing[0]+a.info.spacing[0]%
2+a.info.padding[3],a.insertedRect.y+a.info.spacing[1]+a.info.spacing[1]%2+a.info.padding[0],c.width,c.height)}a.charInfoResult.x=a.insertedRect.x+a.info.spacing[0]+a.info.spacing[0]%2+a.info.padding[3];a.charInfoResult.y=a.insertedRect.y+a.info.spacing[1]+a.info.spacing[1]%2+a.info.padding[0];a.charInfoResult.width=c.width;a.charInfoResult.height=c.height;if(a.charInfoResult.x+a.charInfoResult.width>a.sizeLevel||a.charInfoResult.y+a.charInfoResult.height>a.sizeLevel){console.log(a);return}a.charInfoResult.page=
a.currentPageIndex;a.isKoreanFontData&&(a.charInfoResult.xoffset=a.offset.x,a.charInfoResult.yoffset=a.offset.y,a.charInfoResult.xadvance=a.xAdvance);a.drawInfos=null}else a.pageResult.push({page:a.currentPage,texture:a.currentCanvas,name:this.FormatFileName(a.fileName,a.pageResult.length)}),a.currentPage=new Node(new Rect(0,0,a.sizeLevel,a.sizeLevel)),a.currentCanvas=new CanvasView(a.sizeLevel,a.sizeLevel),a.currentPageIndex++,b--,a.events.pageCreated&&a.events.pageCreated(a.currentPage,a.currentCanvas);
b++}a.events.progress&&a.events.progress(b/a.chars.length,a.charCode);setTimeout(this.DrawFntGlyph.bind(this,a,b),HangulAtlasEditor.RENDER_SPEED)}else{a.pageResult.push({page:a.currentPage,texture:a.currentCanvas,name:this.FormatFileName(a.fileName,a.pageResult.length)});d=[];for(e=0;e<a.pageResult.length;e++)d.push(a.pageResult[e].name);a.result.pages=d;a.result.chars=a.charResult;a.events.progress&&a.events.progress(1,45);a.events.done&&a.events.done(a.fileName,this.ExportFntData(a.result),a.pageResult)}}catch(l){a.events.error&&
a.events.error(l)}};HangulAtlasEditor.FormatFileName=function(a,b){return a+"_"+b.toString().padStart(2,"0")+".png"};
HangulAtlasEditor.ExportFntData=function(a){var b='<?xml version="1.0"?>\n<font>\n  <info';for(var d in a.info)b+=" "+d+'="'+a.info[d]+'"';a.common.pages=a.pages.length;b+="/>\n  <common";for(d in a.common)b+=" "+d+'="'+a.common[d]+'"';b+="/>\n  <pages>\n";for(d in a.pages)b+='    <page id="'+d+'" file="'+a.pages[d]+'" />\n';b=b+'  </pages>\n  <chars count="'+(a.chars.length+'">\n');for(d in a.chars){b+="    <char";for(var e in a.chars[d])b+=" "+e+'="'+a.chars[d][e]+'"';b+=" />\n"}var f;b=b+'  </chars>\n  <kernings count="'+
(a.kernings.length+'">\n');for(d in a.kernings){var g=a.kernings[d].first;(f=g>=this.UNICODE_ALPHABET_START&&g<=this.UNICODE_ALPHABET_END&&this.GetAlphabetType(g)!==this.AlphabetType.None)||(f=g>=this.UNICODE_START&&g<=this.UNICODE_END);f&&(a.kernings[d].amount=0);g=a.kernings[d].second;(f=g>=this.UNICODE_ALPHABET_START&&g<=this.UNICODE_ALPHABET_END&&this.GetAlphabetType(g)!==this.AlphabetType.None)||(f=g>=this.UNICODE_START&&g<=this.UNICODE_END);f&&(a.kernings[d].amount=0);b+="    <kerning";for(e in a.kernings[d])b+=
" "+e+'="'+a.kernings[d][e]+'"';b+=" />\n"}return b+"  </kernings>\n</font>\n"};HangulAtlasEditor.GetAlphabetType=function(a){a=String.fromCharCode(a);return-1!==this.UNICODE_CONSONANTS.indexOf(a)?this.AlphabetType.Consonant:-1!==this.UNICODE_VOWELS.indexOf(a)?this.AlphabetType.Vowel:this.AlphabetType.None};HangulAtlasEditor.CopyObjectRecursive=function(a){var b=a;if("object"===typeof a){b=Array.isArray(a)?[]:{};for(var d in a){var e=typeof a[d];b[d]="object"===e?this.CopyObjectRecursive(a[d]):a[d]}}return b};
function CanvasView(a,b){this.Element=document.createElement("canvas");this.Context=this.Element.getContext("2d");this.Element.width=a||512;this.Element.height=b||512};