var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
function Main(){this.Initialize()}
Main.Initialize=function(){this.Initialized||(this.InitializeView(),this.DKBAtlasInput=document.getElementById("DKBAtlasInput"),this.DKBAtlasInput.addEventListener("click",this.DKBAtlasInput_Click.bind(this)),this.DKBAtlasInput.addEventListener("change",this.DKBAtlasInput_Change.bind(this)),this.DKBAtlasTexture=new Image,this.FntAtlasInput=document.getElementById("FntAtlasInput"),this.FntAtlasInput.addEventListener("click",this.FntAtlasInput_Click.bind(this)),this.FntAtlasInput.addEventListener("change",this.FntAtlasInput_Change.bind(this)),
this.TextureDemensionInput=document.getElementById("TextureDemensionInput"),this.IncludeMinimumKoreanCharactersInput=document.getElementById("IncludeMinimumKoreanCharactersInput"),this.IncludeMinimumKoreanCharactersInput.addEventListener("change",this.IncludeMinimumKoreanCharactersInput_Change.bind(this)),this.IncludeMinimumKoreanCharacters=!0,this.AdditionalKoreanCharactersInput=document.getElementById("AdditionalKoreanCharactersInput"),this.OffsetXInput=document.getElementById("OffsetXInput"),this.OffsetYInput=
document.getElementById("OffsetYInput"),this.OffsetXInput.value=0,this.OffsetYInput.value=0,this.AdvanceXInput=document.getElementById("AdvanceXInput"),this.GenerateButton=document.getElementById("GenerateButton"),this.GenerateButton.addEventListener("click",this.GenerateButton_Click.bind(this)),this.ZipFile=null,this.DownloadZipButton=document.getElementById("DownloadZipButton"),this.DownloadZipButton.addEventListener("click",this.DownloadZipButton_Click.bind(this)),this.DownloadZipButton.setAttribute("disabled",
""),this.ProgressLabel=document.getElementById("ProgressLabel"),this.GenerateViewContainer=document.getElementById("GenerateViewContainer"),this.RenderingPreviewContainer=document.getElementById("RenderingPreviewContainer"),this.RenderingPreviewListContainer=document.getElementById("RenderingPreviewListContainer"),this.RenderingPreview=null,this.FntOutputContainer=document.createElement("pre"),this.FntOutput=document.createElement("code"),this.FntOutputContainer.appendChild(this.FntOutput),this.PIXIViewContainer=
document.getElementById("PIXIViewContainer"),this.PIXIViewTextLabel=document.getElementById("PIXIViewTextLabel"),this.PIXIViewTextInput=document.getElementById("PIXIViewTextInput"),this.PIXIViewTextInput.addEventListener("input",this.PIXIViewTextInput_Change.bind(this)),this.PIXIViewTextInputCache=Strings.PIXI_PARAGRAPH,this.PIXIView=null,this.SetUIStrings(Strings.UI),this.ProgressLabel_Pages=0,this.Initialized=!0,document.body.removeAttribute("pending"))};
Main.SetUIStrings=function(a){document.title=a.TITLE;this.DKBTextureLabel=document.getElementById("DKBTextureLabel");this.DKBTextureHelp=document.getElementById("DKBTextureHelp");this.FntAtlasLabel=document.getElementById("FntAtlasLabel");this.FntAtlasHelp=document.getElementById("FntAtlasHelp");this.TextureSizeLabel=document.getElementById("TextureSizeLabel");this.TextureSizeHelp=document.getElementById("TextureSizeHelp");this.IncludeMinimumKoreanCharactersLabel=document.getElementById("IncludeMinimumKoreanCharactersLabel");
this.IncludeMinimumKoreanCharactersHelp=document.getElementById("IncludeMinimumKoreanCharactersHelp");this.AdditionalKoreanCharactersLabel=document.getElementById("AdditionalKoreanCharactersLabel");this.AdditionalKoreanCharactersHelp=document.getElementById("AdditionalKoreanCharactersHelp");this.OffsetsLabel=document.getElementById("OffsetsLabel");this.OffsetsHelp=document.getElementById("OffsetsHelp");this.AdvanceLabel=document.getElementById("AdvanceLabel");this.AdvanceHelp=document.getElementById("AdvanceHelp");
this.DKBTextureLabel.innerText=a.DKBFILE;this.DKBTextureHelp.innerHTML=a.HELP.DKBFILE;this.FntAtlasLabel.innerText=a.FNTFILE;this.FntAtlasHelp.innerHTML=a.HELP.FNTFILE;this.TextureSizeLabel.innerText=a.TEXTURE_SIZE;this.TextureSizeHelp.innerHTML=a.HELP.TEXTURE_SIZE;this.IncludeMinimumKoreanCharactersLabel.innerText=a.INCLUDE_MINIMUM_KOREAN_CHARACTERS;this.IncludeMinimumKoreanCharactersHelp.innerHTML=a.HELP.INCLUDE_MINIMUM_KOREAN_CHARACTERS;this.AdditionalKoreanCharactersLabel.innerText=a.ADDITIONAL_KOREAN_CHARACTERS;
this.AdditionalKoreanCharactersHelp.innerHTML=a.HELP.ADDITIONAL_KOREAN_CHARACTERS;this.GenerateButton.innerText=a.GENERATE_BUTTON;this.DownloadZipButton.innerText=a.DOWNLOAD_ZIP;this.OffsetsLabel.innerText=a.OFFSETS;this.OffsetsHelp.innerHTML=a.HELP.OFFSETS;this.AdvanceLabel.innerText=a.ADVANCE;this.AdvanceHelp.innerHTML=a.HELP.ADVANCE;this.ProgressLabel.innerHTML=Strings.READY;a=document.getElementById("About");var b;a=$jscomp.makeIterator(a.children);for(b=a.next();!b.done;b=a.next()){var c=b.value;
!c.id||6>=c.id.length||(b=c.id.substring(6),b in Strings.ABOUT&&(c.innerHTML=Strings.ABOUT[b]))}};Main.DKBAtlasInput_Click=function(a){this.DKBAtlasInput.value=null};Main.DKBAtlasInput_Change=function(a){if(a=(a.target||window.event.srcElement).files[0])if(FileReader){var b=new FileReader;b.addEventListener("load",this.DKBAtlasInput_Load.bind(this));b.readAsDataURL(a)}else this.DKBAtlasInput.value=null,alert(Strings.NOT_SUPPORTED_BROWSER);else this.DKBAtlasInput.value=null,alert(Strings.NOT_SELECTED_DKB)};
Main.DKBAtlasInput_Load=function(a){a.currentTarget instanceof FileReader?(this.DKBAtlasTexture.addEventListener("load",Main.DKBAtlasInput_Load.bind(this)),this.DKBAtlasTexture.src=a.currentTarget.result):(HangulAtlasEditor.SetDKBAtlasTexture(this.DKBAtlasTexture),HangulAtlasEditor.IsDKBTextureLoaded&&(this.AdvanceXInput.value=HangulAtlasEditor.DKBHorizontalUnit))};Main.FntAtlasInput_Click=function(a){this.FntAtlasInput.value=null};
Main.FntAtlasInput_Change=function(a){var b=[];a=$jscomp.makeIterator((a.target||window.event.srcElement).files);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.name.endsWith(".png"))b.push(c);else if(c.name.endsWith(".fnt")&&!e)var e=c;else{this.FntAtlasInput.value=null;alert(Strings.NOT_VALID_FNT);return}e&&0!==b.length?(a=e.name,this.FileName=a.substring(0,a.lastIndexOf(".")),FileReader?(HangulAtlasEditor.ClearFntAtlasTexture(),fileReader=new FileReader,fileReader.PngFiles=b,fileReader.addEventListener("load",
this.FntAtlasInput_DataLoad.bind(this)),fileReader.readAsText(e)):alert(Strings.NOT_SUPPORTED_BROWSER)):(this.FntAtlasInput.value=null,alert(Strings.NOT_VALID_FNT))};
Main.FntAtlasInput_DataLoad=function(a){if(a.currentTarget instanceof FileReader){HangulAtlasEditor.LoadFntXml(a.currentTarget.result);var b=[];if(HangulAtlasEditor.FntData){for(var c,e=0,f=$jscomp.makeIterator(HangulAtlasEditor.FntData.pages),d=f.next();!d.done;d=f.next()){var h=d.value;c=!1;var g=$jscomp.makeIterator(a.currentTarget.PngFiles);for(d=g.next();!d.done;d=g.next())if(d=d.value,d.name===h){c=!0;break}b[e++]=c}if(-1!==b.indexOf(!1))alert(Strings.NOT_VALID_FNT);else for(a=$jscomp.makeIterator(a.currentTarget.PngFiles),
d=a.next();!d.done;d=a.next())d=d.value,b=new FileReader,b.file=d,b.addEventListener("load",this.FntAtlasInput_ImageLoad.bind(this)),b.readAsDataURL(d)}}};Main.FntAtlasInput_ImageLoad=function(a){if(a.currentTarget instanceof FileReader){var b=new Image;b.file=a.currentTarget.file;b.addEventListener("load",Main.FntAtlasInput_ImageLoad.bind(this));b.src=a.currentTarget.result}else HangulAtlasEditor.AddFntAtlasTexture(a.currentTarget.file.name,a.currentTarget)};
Main.IncludeMinimumKoreanCharactersInput_Change=function(a){this.IncludeMinimumKoreanCharacters=a.currentTarget.checked};
Main.GenerateButton_Click=function(a){this.RenderingPreviewContainer.contains(this.FntOutputContainer)&&this.RenderingPreviewContainer.removeChild(this.FntOutputContainer);this.RenderingPreview=null;this.FntOutput.innerText="";this.RenderingPreviewContainer.innerHTML="";this.RenderingPreviewListContainer.innerHTML="";this.DownloadZipButton.setAttribute("disabled","");a={x:parseInt(this.OffsetXInput.value),y:parseInt(this.OffsetYInput.value)};var b=parseInt(this.AdvanceXInput.value);HangulAtlasEditor.GenerateFnt({sizeLevel:this.TextureDemensionInput.value,
fileName:this.FileName,offset:a,xAdvance:b,includeMinimumKoreanCharacters:this.IncludeMinimumKoreanCharacters,additionalKoreanCharacters:this.AdditionalKoreanCharactersInput.value,progress:this.GenerateFnt_Progress.bind(this),pageCreated:this.GenerateFnt_PageCreated.bind(this),done:this.GenerateFnt_Done.bind(this),error:this.GenerateFnt_Error.bind(this)})&&(this.ProgressLabel.innerHTML=Strings.GENERATE_BEGIN,this.ProgressLabel_Pages=0,this.GenerateViewContainer.style.display="",this.PIXIViewTextInput.style.display=
"",document.body.setAttribute("pending",""),this.PIXIView&&this.PIXIView.Dispose())};Main.GenerateFnt_Progress=function(a,b){var c=b.toString(16).toUpperCase().padStart(4,"0");this.ProgressLabel.innerHTML=Strings.GENERATE_PROGRESS+(" ("+Math.floor(100*a)+"%)<br>")+Strings.GENERATE_PAGES+(" : "+this.ProgressLabel_Pages+"<br>")+Strings.GENERATE_PROCESSING_GLYPH+(" : "+String.fromCharCode(b)+" (U+"+c+")")};
Main.GenerateFnt_PageCreated=function(a,b){this.RenderingPreview&&(this.RenderingPreviewContainer.removeChild(this.RenderingPreview),this.RenderingPreviewListContainer.appendChild(this.RenderingPreview));this.RenderingPreview=b.Element;this.RenderingPreviewContainer.appendChild(this.RenderingPreview);this.ProgressLabel_Pages++};
Main.GenerateFnt_Done=function(a,b,c){this.FntOutput.innerText=b;this.RenderingPreviewContainer.appendChild(this.FntOutputContainer);this.PIXIView=new PIXIView;this.ProgressLabel.innerHTML=Strings.GENERATE_ZIPPING;var e=new JSZip;e.file(a+".fnt",b);var f;c=$jscomp.makeIterator(c);for(f=c.next();!f.done;f=c.next()){var d=f.value;f=d.texture.Element.toDataURL();this.PIXIView.AddAssetToLoader(d.name,f);f=f.replace(/^data:image\/(png|jpg);base64,/,"");e.file(d.name,f,{base64:!0})}this.PIXIView.AddAssetToLoader(a,
"data:text/fnt;base64,"+base64encode(b));this.PIXIView.InitializeText(HangulAtlasEditor.FntData.info.face,this.PIXIView_Load.bind(this));this.PIXIViewContainer.appendChild(this.PIXIView.Element);e.generateAsync({type:"blob"}).then(this.GenerateFnt_DownloadZip.bind(this))};Main.GenerateFnt_Error=function(a){console.error(a);alert(Strings.GENERATE_ERROR+"\n"+a.message+"\n"+Strings.GENERATE_ERROR_ADDITIONAL);document.body.removeAttribute("pending")};
Main.GenerateFnt_DownloadZip=function(a){document.body.removeAttribute("pending");a?(this.ZipFile=a,this.DownloadZipButton.removeAttribute("disabled"),this.ProgressLabel.innerHTML=Strings.GENERATE_DONE):this.ProgressLabel.innerHTML=Strings.GENERATE_FAILED_ZIP};Main.DownloadZipButton_Click=function(a){this.ZipFile&&saveAs(this.ZipFile,"output.zip")};
Main.PIXIView_Load=function(){this.GenerateViewContainer.style.display="none";this.PIXIViewTextInput.style.display="block";this.PIXIViewTextInputCache=this.PIXIViewTextInput.value||this.PIXIViewTextInputCache;this.PIXIViewTextInput.value=this.PIXIViewTextInputCache;this.PIXIView.SetText(this.PIXIViewTextInputCache)};Main.PIXIViewTextInput_Change=function(a){document.body.getAttribute("pending")?a.preventDefault():this.PIXIView&&this.PIXIView.SetText(this.PIXIViewTextInput.value)};
Main.InitializeView=function(){this.Views=[];this.ViewContainer=document.getElementById("View");for(var a=$jscomp.makeIterator(this.ViewContainer.children),b=a.next();!b.done;b=a.next())b=b.value,this.Views.push(b.id);a=document.getElementById("Header");var c=$jscomp.makeIterator(this.Views);for(b=c.next();!b.done;b=c.next()){b=b.value;var e=document.createElement("span");e.setAttribute("view",b);e.classList.add("item");b in Strings.HEADERS&&(e.innerText=Strings.HEADERS[b]);e.addEventListener("click",
this.Header_Click.bind(this));a.appendChild(e)}a.children[1].click()};Main.Header_Click=function(a){a=a.currentTarget;var b=a.getAttribute("view");this.ViewContainer.setAttribute("view",b);this.CurrentViewItem&&this.CurrentViewItem.classList.remove("active");a.classList.add("active");this.CurrentViewItem=a};window.addEventListener("load",Main.bind(Main));